import Head from "next/head"

import styles from "@/styles/Home.module.css"

import { Button, styled } from "@mui/material"

// icons-material
import AddIcon from "@mui/icons-material/Add"

import MainPage from "@/components/Home/MainPage"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPage />
    </>
  )
}
